### ISSUE TITLE
I wanna know when the source code will be open?

### ISSUE THREAD

**Issue by long123long** [thunlp/AGE#1]

**Comment by cgq15** [comment]
Thanks for your attention. We have opened the source code!

**Comment by lilinbaba** [comment]
请问您能把链路预测的train.py添加上去吗？没有找到链路预测试验的运行代码

**Comment by lilinbaba** [comment]
请问pubmed数据集在链路预测任务上的效果如何？链路预测试验为什么只在两个引文数据集上做，而不是全部？
