### ISSUE TITLE
The negative threshold choose

### ISSUE THREAD

**Issue by jiajun-gnn** [thunlp/AGE#10]
As shown in the Readme document, I am confused about why a positive threshold is decaying when doing adaptive learning, but the negative is increasing when training.

**Comment by cgq15** [comment]
Hi, as we said in the paper, 
"Inspired by the idea of curriculum learning [1], we design a specific update strategy for rpos and rneg to control the size of training set. At the beginning of training process, more samples are selected for the encoder to find rough cluster patterns. After that, samples with higher confidence are remained for training, forcing the encoder to capture refined patterns. "

**Comment by jiajun-gnn** [comment]
thank you very much, I understand it!
