### ISSUE TITLE
Ability to deal with multi-graph tasks

### ISSUE THREAD

**Issue by island255** [thunlp/AGE#2]
Thanks for your outstanding work!

When I am reading your paper, I find that two experiment including node clustering and link prediction is carried out. This may be done in a single graph. And I wonder if I can use AGE to do some multi-graph tasks, such as comparing nodes in different graphs or comparing different graphs.

**Comment by cgq15** [comment]
Thanks for your attention. Using AGE to deal with multi-graph tasks is an interesting idea. But I think you should ensure that nodes or graphs are comparable.
