### ISSUE TITLE
Train on different graphs

### ISSUE THREAD

**Issue by SasCezar** [thunlp/AGE#4]
Hi, 

I'm trying to understand if the code can be generalized to multiple graphs. I don't want to compare them as in this [issue](https://github.com/thunlp/AGE/issues/2), but I have a dataset with multiple smaller graphs (1000 nodes (variable) x 500 features (fixed)), and I want to annotate the edges of each one. However, from what I understood, all the datasets you use have only a single, large graph.

I have two possible solutions for how I can achieve this. 

1. Combine all in a single large dataset and then use the same code, however, this solution doesn't scale to new graphs and also doesn't scale well for the GPU memory usage.

2. The alternative is to use batching from torch-geometric and then apply the Laplacian on the batch and then sample positives and negatives examples from each batch and iterate for a larger number of epochs. However, I think that the Laplacian smoothing might cause some issues from the different graphs, as their feature might be very different. Maybe, I can just use a batch of one, apply the smoothing, and sample large? 

Any tips or suggestions about which solution would be better?

NOTE: I don't have any labeled data, so my only measures are unsupervised (eg silhouette, modularity).

Thanks

**Comment by cgq15** [comment]
Hi, I think the second solution would be better. For graphs in the same domain, their Laplacian matrices are supposed to be similar. You can train the encoder on some small graphs and generalize to other graphs. However, for graphs in different domains, AGE can not generalize to unseen graphs.
