### ISSUE TITLE
模型的适用性问题

### ISSUE THREAD

**Issue by A-song-of-Ice-and-Fire** [thunlp/AGE#6]
您好！首先感谢您在图嵌入方面的工作。请问该模型能否适用于有权图，另外它在无属性的情况下表现依然优异吗？

**Comment by cgq15** [comment]
您好，AGE可以适用于有权图。在无属性的情况下，因为要直接训练节点的表示向量，所以对特征的Laplacian smoothing就没有了意义，预计表现一般。

**Comment by A-song-of-Ice-and-Fire** [comment]
您的解答对我非常有帮助，દ ᵕ̈ ૩ ​​​谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月13日(星期二) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thunlp/AGE] 模型的适用性问题 (#6)
