### ISSUE TITLE
Could you release Implementation of baselines?

### ISSUE THREAD

**Issue by Luo-Yihong** [thunlp/AGE#7]
Thanks for your great work!

I think if you could release Implementation of baselines it would be pretty helpful to the community~

**Comment by cgq15** [comment]
Hi, I used public releases of baselines as follows:
ARGA & ARVGA: https://github.com/GRAND-Lab/ARGA
AGC: https://github.com/karenlatong/AGC-master
DAEGC: https://github.com/Tiger101010/DAEGC
GALA: https://github.com/sseung0703/GALA_TF2.0
